#!/usr/bin/env bash
set -euo pipefail

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%'
  IDENTIFIED WITH mysql_native_password BY '${MYSQL_APP_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${CANAL_MYSQL_USER}'@'%'
  IDENTIFIED WITH mysql_native_password BY '${CANAL_MYSQL_PASSWORD}';

GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT
  ON *.* TO '${CANAL_MYSQL_USER}'@'%';

FLUSH PRIVILEGES;
SQL
